//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTHUVIEN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyThuVienEntities1 : DbContext
    {
        public QuanLyThuVienEntities1()
            : base("name=QuanLyThuVienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<DOCGIA> DOCGIAs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUMUON> PHIEUMUONs { get; set; }
        public virtual DbSet<PHIEUTRA> PHIEUTRAs { get; set; }
        public virtual DbSet<QLMUONTRA> QLMUONTRAs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
    
        public virtual ObjectResult<GetAC_Result> GetAC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAC_Result>("GetAC");
        }
    
        public virtual ObjectResult<GetDG_Result> GetDG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDG_Result>("GetDG");
        }
    
        public virtual ObjectResult<GetNV_Result> GetNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNV_Result>("GetNV");
        }
    
        public virtual ObjectResult<GetPM_Result> GetPM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPM_Result>("GetPM");
        }
    
        public virtual ObjectResult<GetPT_Result> GetPT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPT_Result>("GetPT");
        }
    
        public virtual ObjectResult<GetQlMT_Result> GetQlMT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQlMT_Result>("GetQlMT");
        }
    
        public virtual ObjectResult<GetS_Result> GetS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetS_Result>("GetS");
        }
    
        public virtual int ThemDG(string hoTen, string gioiTinh, Nullable<System.DateTime> namSinh)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var namSinhParameter = namSinh.HasValue ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDG", hoTenParameter, gioiTinhParameter, namSinhParameter);
        }
    
        public virtual int ThemNV(string hoTen, string tenDangNhap, Nullable<System.DateTime> namSinh, string diaChi)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var namSinhParameter = namSinh.HasValue ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNV", hoTenParameter, tenDangNhapParameter, namSinhParameter, diaChiParameter);
        }
    
        public virtual int ThemPM(Nullable<int> maNV, Nullable<int> maSach, Nullable<System.DateTime> ngayMuon, Nullable<System.DateTime> ngayPhaiTra)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var ngayMuonParameter = ngayMuon.HasValue ?
                new ObjectParameter("NgayMuon", ngayMuon) :
                new ObjectParameter("NgayMuon", typeof(System.DateTime));
    
            var ngayPhaiTraParameter = ngayPhaiTra.HasValue ?
                new ObjectParameter("NgayPhaiTra", ngayPhaiTra) :
                new ObjectParameter("NgayPhaiTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemPM", maNVParameter, maSachParameter, ngayMuonParameter, ngayPhaiTraParameter);
        }
    
        public virtual int ThemPT(Nullable<int> maPhieuMuon, Nullable<int> maSach, Nullable<System.DateTime> ngayTra)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemPT", maPhieuMuonParameter, maSachParameter, ngayTraParameter);
        }
    
        public virtual int ThemQLMT(Nullable<int> maDocGia, Nullable<int> maSach, Nullable<int> maPhieuMuon, Nullable<int> maPhieuTra, string tinhTrang)
        {
            var maDocGiaParameter = maDocGia.HasValue ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var maPhieuTraParameter = maPhieuTra.HasValue ?
                new ObjectParameter("MaPhieuTra", maPhieuTra) :
                new ObjectParameter("MaPhieuTra", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemQLMT", maDocGiaParameter, maSachParameter, maPhieuMuonParameter, maPhieuTraParameter, tinhTrangParameter);
        }
    
        public virtual int ThemS(string tenSach, string tacGia, string theLoai, string nhaXuatBan, Nullable<int> giaSach, Nullable<int> soLuong, string tinhTrang)
        {
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var tacGiaParameter = tacGia != null ?
                new ObjectParameter("TacGia", tacGia) :
                new ObjectParameter("TacGia", typeof(string));
    
            var theLoaiParameter = theLoai != null ?
                new ObjectParameter("TheLoai", theLoai) :
                new ObjectParameter("TheLoai", typeof(string));
    
            var nhaXuatBanParameter = nhaXuatBan != null ?
                new ObjectParameter("NhaXuatBan", nhaXuatBan) :
                new ObjectParameter("NhaXuatBan", typeof(string));
    
            var giaSachParameter = giaSach.HasValue ?
                new ObjectParameter("GiaSach", giaSach) :
                new ObjectParameter("GiaSach", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemS", tenSachParameter, tacGiaParameter, theLoaiParameter, nhaXuatBanParameter, giaSachParameter, soLuongParameter, tinhTrangParameter);
        }
    
        public virtual int SuaDg(Nullable<int> maDocGia, Nullable<int> orinMaDocGia, string hoTen, string gioiTinh, Nullable<System.DateTime> namSinh)
        {
            var maDocGiaParameter = maDocGia.HasValue ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(int));
    
            var orinMaDocGiaParameter = orinMaDocGia.HasValue ?
                new ObjectParameter("OrinMaDocGia", orinMaDocGia) :
                new ObjectParameter("OrinMaDocGia", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var namSinhParameter = namSinh.HasValue ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaDg", maDocGiaParameter, orinMaDocGiaParameter, hoTenParameter, gioiTinhParameter, namSinhParameter);
        }
    
        public virtual int XoaDg(Nullable<int> maDocGia)
        {
            var maDocGiaParameter = maDocGia.HasValue ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDg", maDocGiaParameter);
        }
    
        public virtual int SuaNV(Nullable<int> maNV, Nullable<int> orinMaNV, string hoTen, string tenDangNhap, Nullable<System.DateTime> namSinh, string diaChi)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var orinMaNVParameter = orinMaNV.HasValue ?
                new ObjectParameter("OrinMaNV", orinMaNV) :
                new ObjectParameter("OrinMaNV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var namSinhParameter = namSinh.HasValue ?
                new ObjectParameter("NamSinh", namSinh) :
                new ObjectParameter("NamSinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNV", maNVParameter, orinMaNVParameter, hoTenParameter, tenDangNhapParameter, namSinhParameter, diaChiParameter);
        }
    
        public virtual int SuaPM(Nullable<int> maPhieuMuon, Nullable<int> orinMaPhieuMuon, Nullable<int> maNV, Nullable<int> maSach, Nullable<System.DateTime> ngayMuon, Nullable<System.DateTime> ngayPhaiTra)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var orinMaPhieuMuonParameter = orinMaPhieuMuon.HasValue ?
                new ObjectParameter("OrinMaPhieuMuon", orinMaPhieuMuon) :
                new ObjectParameter("OrinMaPhieuMuon", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var ngayMuonParameter = ngayMuon.HasValue ?
                new ObjectParameter("NgayMuon", ngayMuon) :
                new ObjectParameter("NgayMuon", typeof(System.DateTime));
    
            var ngayPhaiTraParameter = ngayPhaiTra.HasValue ?
                new ObjectParameter("NgayPhaiTra", ngayPhaiTra) :
                new ObjectParameter("NgayPhaiTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaPM", maPhieuMuonParameter, orinMaPhieuMuonParameter, maNVParameter, maSachParameter, ngayMuonParameter, ngayPhaiTraParameter);
        }
    
        public virtual int SuaPT(Nullable<int> maPhieuTra, Nullable<int> orinMaPhieuTra, Nullable<int> maPhieuMuon, Nullable<int> maSach, Nullable<System.DateTime> ngayTra)
        {
            var maPhieuTraParameter = maPhieuTra.HasValue ?
                new ObjectParameter("MaPhieuTra", maPhieuTra) :
                new ObjectParameter("MaPhieuTra", typeof(int));
    
            var orinMaPhieuTraParameter = orinMaPhieuTra.HasValue ?
                new ObjectParameter("OrinMaPhieuTra", orinMaPhieuTra) :
                new ObjectParameter("OrinMaPhieuTra", typeof(int));
    
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaPT", maPhieuTraParameter, orinMaPhieuTraParameter, maPhieuMuonParameter, maSachParameter, ngayTraParameter);
        }
    
        public virtual int SuaS(Nullable<int> maSach, Nullable<int> orinMaSach, string tenSach, string tacGia, string theLoai, string nhaXuatBan, Nullable<int> giaSach, Nullable<int> soLuong, string tinhTrang)
        {
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var orinMaSachParameter = orinMaSach.HasValue ?
                new ObjectParameter("OrinMaSach", orinMaSach) :
                new ObjectParameter("OrinMaSach", typeof(int));
    
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var tacGiaParameter = tacGia != null ?
                new ObjectParameter("TacGia", tacGia) :
                new ObjectParameter("TacGia", typeof(string));
    
            var theLoaiParameter = theLoai != null ?
                new ObjectParameter("TheLoai", theLoai) :
                new ObjectParameter("TheLoai", typeof(string));
    
            var nhaXuatBanParameter = nhaXuatBan != null ?
                new ObjectParameter("NhaXuatBan", nhaXuatBan) :
                new ObjectParameter("NhaXuatBan", typeof(string));
    
            var giaSachParameter = giaSach.HasValue ?
                new ObjectParameter("GiaSach", giaSach) :
                new ObjectParameter("GiaSach", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaS", maSachParameter, orinMaSachParameter, tenSachParameter, tacGiaParameter, theLoaiParameter, nhaXuatBanParameter, giaSachParameter, soLuongParameter, tinhTrangParameter);
        }
    
        public virtual int XoaNV(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNV", maNVParameter);
        }
    
        public virtual int XoaPM(Nullable<int> maPhieuMuon)
        {
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaPM", maPhieuMuonParameter);
        }
    
        public virtual int XoaPT(Nullable<int> maPhieuTra)
        {
            var maPhieuTraParameter = maPhieuTra.HasValue ?
                new ObjectParameter("MaPhieuTra", maPhieuTra) :
                new ObjectParameter("MaPhieuTra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaPT", maPhieuTraParameter);
        }
    
        public virtual int XoaS(Nullable<int> maSach)
        {
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaS", maSachParameter);
        }
    
        public virtual int SuaQLMT(Nullable<int> maQL, Nullable<int> orinMaQL, Nullable<int> maDocGia, Nullable<int> maSach, Nullable<int> maPhieuMuon, Nullable<int> maPhieuTra, string tinhTrang)
        {
            var maQLParameter = maQL.HasValue ?
                new ObjectParameter("MaQL", maQL) :
                new ObjectParameter("MaQL", typeof(int));
    
            var orinMaQLParameter = orinMaQL.HasValue ?
                new ObjectParameter("OrinMaQL", orinMaQL) :
                new ObjectParameter("OrinMaQL", typeof(int));
    
            var maDocGiaParameter = maDocGia.HasValue ?
                new ObjectParameter("MaDocGia", maDocGia) :
                new ObjectParameter("MaDocGia", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var maPhieuMuonParameter = maPhieuMuon.HasValue ?
                new ObjectParameter("MaPhieuMuon", maPhieuMuon) :
                new ObjectParameter("MaPhieuMuon", typeof(int));
    
            var maPhieuTraParameter = maPhieuTra.HasValue ?
                new ObjectParameter("MaPhieuTra", maPhieuTra) :
                new ObjectParameter("MaPhieuTra", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaQLMT", maQLParameter, orinMaQLParameter, maDocGiaParameter, maSachParameter, maPhieuMuonParameter, maPhieuTraParameter, tinhTrangParameter);
        }
    
        public virtual int XoaAC(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaAC", maNVParameter);
        }
    
        public virtual int XoaQLMT(Nullable<int> maQL)
        {
            var maQLParameter = maQL.HasValue ?
                new ObjectParameter("MaQL", maQL) :
                new ObjectParameter("MaQL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaQLMT", maQLParameter);
        }
    
        public virtual ObjectResult<TimS_Result> TimS(string tenSach)
        {
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimS_Result>("TimS", tenSachParameter);
        }
    
        public virtual ObjectResult<DangNhap_Result> DangNhap(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DangNhap_Result>("DangNhap", tenDangNhapParameter, matKhauParameter);
        }
    }
}
